config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability
  
  def initialize(user)

    can :read, Post

    if user.present?
      can :create, Post
      can [:update, :destroy], Post, user_id: user.id 
      if user.admin?
        can :destroy, Post
      end
    end
    
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true

  has_attached_file :image, styles: { medium: "400x300>", thumb: "286x180>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user

  self.per_page = 10

  scope :search, ->(query) { where("title like ?", "%#{query}%") }
  scope :myposts, ->(id) { where("user_id like ?", "%#{id}%") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :nick, :city, :state, presence: true
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:admin, :nick, :phoneNumber, :zipcode, :state, :city, :neighborhood, :whatsapp, :telegram])
        devise_parameter_sanitizer.permit(:account_update, keys: [:admin, :nick, :phoneNumber, :zipcode, :state, :city, :neighborhood, :whatsapp, :telegram])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:search]
      @posts = Post.all.paginate(page: params[:page]).search(params[:search]).order('id DESC')
    elsif params[:myposts]  
      @posts = Post.all.paginate(page: params[:page]).myposts(params[:myposts]).order('id DESC')
    else
      @posts = Post.all.paginate(page: params[:page]).order('id DESC')
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.create(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Ep3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>

<body style="background-color: #f2f4f8;">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to 'Home', posts_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent" >
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
                <li class="nav-item dropdown dropleft text-right">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <%= current_user.email %>
                    </a>
                    <div class="dropdown-menu mb-3" aria-labelledby="navbarDropdown">
                        <p class="dropdown-item"><%= current_user.nick %></p>
                        <hr>
                        <%= link_to 'My posts', posts_path(:myposts => current_user.id), class: "dropdown-item" %>
                        <%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item" %>
                        <div class="dropdown-divider"></div>
                        <%= link_to 'Quit', destroy_user_session_path, class: "dropdown-item", method: :delete %>
                    </div>
                </li>
                <%= link_to 'New Post', new_post_path, class: "btn btn-primary rounded-pill" %>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Log in', user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
            </li>
            <%= link_to 'New Post', user_session_path, class: "btn btn-primary rounded-pill" %>
          <% end %>  
          </ul> 
        </div>
    </nav>

    <div class="container mt-5 mb-5">
        <%= yield %>
    </div>

</body>

</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |form| %>

  <%= form.input :title, required: true, error: 'Title is mandatory, please specify one' %>
   
  <%= form.input :body, required: true, as: :text, maxlength: 2000, input_html: { :style=> "height: 500px; resize: none;" } %>

  <hr>
  <%= form.input :image, as: :file, class: "custom-file-input" %>

  <hr>
  <%= form.button :submit, class: "btn btn-primary rounded-pill" %>
  <%= link_to 'Cancel', posts_path, class: "btn btn-success rounded-pill" %>
  
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<hr>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="shadow-lg p-3 mb-3 rounded bg-white">
<h1 class="mr-5" >Recents Posts</h1>
<hr>

<%= form_tag(posts_path, method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag("search") %>
    <%= submit_tag("Search") %>
<% end %>
</div>

<% @posts.each do |post| %>
  <div class="card rounded shadow-lg mb-3">
    <div class="row no-gutters">
        <div class="text-center col-md-4" style="background-color: #c3c3c3">
            <%= image_tag post.image.url(:thumb), :class => "card-img-left" %>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><%= post.title %></h5>

                <p class="card-text">
                    <%= post.body[0,120] %>
                        <% if post.body.size > 120 %>
                            [...]
                            <% end %>
                </p>

            </div>
            <div class="card-body text-right">
                <%= link_to 'Show', post, class: "btn btn-primary rounded-pill" %>
            </div>
            <div class="card-footer text-muted">
                <p class="card-text float-left">Last update: <%= post.updated_at %></p>
            </div>
        </div>
    </div>
  </div>
<% end %>
<%= will_paginate @posts %>
<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<hr>
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= link_to 'Back', posts_path, class: "btn btn-primary rounded-pill" %>

  <% if can? :update, @post %>
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning rounded-pill" %>
  <% end %>

  <% if can? :destroy, @post %>
    <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger rounded-pill" %>
  <% end %>
</div>

<div class="row">
<div class="card shadow-lg mt-3 col-lg-8">
  <div class="card-body">
    <h1 class="card-title text-center"><%= @post.title %></h1>
    <hr>
    <div class="text-center"><%= image_tag @post.image.url(:medium) %></div>
    <hr>
    <p class="card-text"><%= simple_format(@post.body) %></p>
    <div class="card-footer text-muted">
    <p class="card-text text-center">Last update: <%= @post.updated_at %></p>
    </div>
  </div>
</div>

<div class="card shadow-lg mt-3 ml-lg-3 col-lg-3">
  <div class="card-body text-center">
    <h5 class="card-title">User: <%= @post.user.nick %></h5>
    <hr>
    <p class="card-text"><%= @post.user.state %></p>
    <p class="card-text"><%= @post.user.city %></p>
    <p class="card-text"><%= @post.user.neighborhood %></p>
    <hr>
    <p class="card-text"><%= @post.user.phoneNumber %></p>
    <p class="card-text"><%= @post.user.email %></p>
  </div>
</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>